services:
  postgresql:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: Homework5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/Homework5
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./src/main/resources/migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: { }

networks:
  backend: { }