spring:
  application:
    name: Hopmework10

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'